<?php

use Illuminate\Database\Seeder;

class LanguagesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('languages')->insert([
            ['language' => 'Afar'],
            ['language' => 'Abkhazian'],
            ['language' => 'Afrikaans'],
            ['language' => 'Amharic'],
            ['language' => 'Arabic'],
            ['language' => 'Assamese'],
            ['language' => 'Aymara'],
            ['language' => 'Azerbaijani'],
            ['language' => 'Bashkir'],
            ['language' => 'Byelorussian'],
            ['language' => 'Bulgarian'],
            ['language' => 'Bihari'],
            ['language' => 'Bislama'],
            ['language' => 'Bengali/Bangla'],
            ['language' => 'Tibetan'],
            ['language' => 'Breton'],
            ['language' => 'Catalan'],
            ['language' => 'Corsican'],
            ['language' => 'Czech'],
            ['language' => 'Welsh'],
            ['language' => 'Danish'],
            ['language' => 'English'],
            ['language' => 'German'],
            ['language' => 'Bhutani'],
            ['language' => 'Greek'],
            ['language' => 'Esperanto'],
            ['language' => 'Spanish'],
            ['language' => 'Estonian'],
            ['language' => 'Basque'],
            ['language' => 'Persian'],
            ['language' => 'Finnish'],
            ['language' => 'Fiji'],
            ['language' => 'Faeroese'],
            ['language' => 'French'],
            ['language' => 'Frisian'],
            ['language' => 'Irish'],
            ['language' => 'Scots/Gaelic'],
            ['language' => 'Galician'],
            ['language' => 'Guarani'],
            ['language' => 'Gujarati'],
            ['language' => 'Hausa'],
            ['language' => 'Hindi'],
            ['language' => 'Croatian'],
            ['language' => 'Hungarian'],
            ['language' => 'Armenian'],
            ['language' => 'Interlingua'],
            ['language' => 'Interlingue'],
            ['language' => 'Inupiak'],
            ['language' => 'Indonesian'],
            ['language' => 'Icelandic'],
            ['language' => 'Italian'],
            ['language' => 'Hebrew'],
            ['language' => 'Japanese'],
            ['language' => 'Yiddish'],
            ['language' => 'Javanese'],
            ['language' => 'Georgian'],
            ['language' => 'Kazakh'],
            ['language' => 'Greenlandic'],
            ['language' => 'Cambodian'],
            ['language' => 'Kannada'],
            ['language' => 'Korean'],
            ['language' => 'Kashmiri'],
            ['language' => 'Kurdish'],
            ['language' => 'Kirghiz'],
            ['language' => 'Latin'],
            ['language' => 'Lingala'],
            ['language' => 'Laothian'],
            ['language' => 'Lithuanian'],
            ['language' => 'Latvian/Lettish'],
            ['language' => 'Malagasy'],
            ['language' => 'Maori'],
            ['language' => 'Macedonian'],
            ['language' => 'Malayalam'],
            ['language' => 'Mongolian'],
            ['language' => 'Moldavian'],
            ['language' => 'Marathi'],
            ['language' => 'Malay'],
            ['language' => 'Maltese'],
            ['language' => 'Burmese'],
            ['language' => 'Nauru'],
            ['language' => 'Nepali'],
            ['language' => 'Dutch'],
            ['language' => 'Norwegian'],
            ['language' => 'Occitan'],
            ['language' => '(Afan)/Oromoor/Oriya'],
            ['language' => 'Punjabi'],
            ['language' => 'Polish'],
            ['language' => 'Pashto/Pushto'],
            ['language' => 'Portuguese'],
            ['language' => 'Quechua'],
            ['language' => 'Rhaeto-Romance'],
            ['language' => 'Kirundi'],
            ['language' => 'Romanian'],
            ['language' => 'Russian'],
            ['language' => 'Kinyarwanda'],
            ['language' => 'Sanskrit'],
            ['language' => 'Sindhi'],
            ['language' => 'Sangro'],
            ['language' => 'Serbo-Croatian'],
            ['language' => 'Singhalese'],
            ['language' => 'Slovak'],
            ['language' => 'Slovenian'],
            ['language' => 'Samoan'],
            ['language' => 'Shona'],
            ['language' => 'Somali'],
            ['language' => 'Albanian'],
            ['language' => 'Serbian'],
            ['language' => 'Siswati'],
            ['language' => 'Sesotho'],
            ['language' => 'Sundanese'],
            ['language' => 'Swedish'],
            ['language' => 'Swahili'],
            ['language' => 'Tamil'],
            ['language' => 'Tegulu'],
            ['language' => 'Tajik'],
            ['language' => 'Thai'],
            ['language' => 'Tigrinya'],
            ['language' => 'Turkmen'],
            ['language' => 'Tagalog'],
            ['language' => 'Setswana'],
            ['language' => 'Tonga'],
            ['language' => 'Turkish'],
            ['language' => 'Tsonga'],
            ['language' => 'Tatar'],
            ['language' => 'Twi'],
            ['language' => 'Ukrainian'],
            ['language' => 'Urdu'],
            ['language' => 'Uzbek'],
            ['language' => 'Vietnamese'],
            ['language' => 'Volapuk'],
            ['language' => 'Wolof'],
            ['language' => 'Xhosa'],
            ['language' => 'Yoruba'],
            ['language' => 'Chinese'],
            ['language' => 'Zulu'],
        ]);
    }
}
